// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQNQ-vG_E7ETNE7o5oOI34OiayVo3PMYs',
    appId: '1:653085125949:web:1923caf4ca72543d0ee954',
    messagingSenderId: '653085125949',
    projectId: 'helper-4a9d3',
    authDomain: 'helper-4a9d3.firebaseapp.com',
    storageBucket: 'helper-4a9d3.appspot.com',
    measurementId: 'G-GN021D07H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAftwZOlTV4hb-X-kR1CKb1pAQGE-Wc7tk',
    appId: '1:653085125949:android:01c4e937b2f1cd3b0ee954',
    messagingSenderId: '653085125949',
    projectId: 'helper-4a9d3',
    storageBucket: 'helper-4a9d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3kjbapSAvjvjuIlfR5spOaGCCn-WrMRM',
    appId: '1:653085125949:ios:66113f61c9d21d240ee954',
    messagingSenderId: '653085125949',
    projectId: 'helper-4a9d3',
    storageBucket: 'helper-4a9d3.appspot.com',
    iosClientId: '653085125949-ml3ka0007r0sa1m69ec7uua9c17ptd05.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3kjbapSAvjvjuIlfR5spOaGCCn-WrMRM',
    appId: '1:653085125949:ios:66113f61c9d21d240ee954',
    messagingSenderId: '653085125949',
    projectId: 'helper-4a9d3',
    storageBucket: 'helper-4a9d3.appspot.com',
    iosClientId: '653085125949-ml3ka0007r0sa1m69ec7uua9c17ptd05.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );
}
